language: bash
sudo: required
cache: apt

# we don't use docker but this triggers travis-ci to provide Ubuntu 14.04
services:
    - docker
before_install:
    - lsb_release -a
    - sudo apt-get update -qq
install:
    - sudo make dependencies
    - make local
script:
    # make test and create Debian package
    - make package
    # locally install package
    - sudo dpkg -i gbvdoc_*.deb
    - sudo service gbvdoc status
    # test against localhost
    - export TEST_URL=6012
    - prove -Ilib -Ilocal/lib/perl5 -v

after_failure:
    - tail -200 /var/log/gbvdoc/error.log

# Release Debian package via GitHub releases on tagged commits
before_deploy:
    - export RELEASE_FILE=$(ls *.deb)
    - echo "deploying $RELEASE_FILE to GitHub releases"
deploy:
    provider: releases
    api_key:
        secure: i5hghT2SgdVUwJz3LMlARvA9/2RvZ3qoRt1UFxkQziRsK1Hz4r2plVcxER4tqUk4ODwxFpDGTB8EE4VZcUfrpa4zaS8tYXNdEvPBviBlNaYP9aX+PETsCNeBkxBNjNrv6Is7WRO4T+lIartK58PTQm/3Mise1+pbRU2F5/ERMNXDFgdX8f2XpDKlS0+NeKNvuukYTWrhhkUvypGsa9ZtxieEUdzX27cB26NJ4o5gsKPao7wU/nX3ZYkT+tUgpD+wZy2O0gLzIuxhVyaBBBG50iIWfi5o84nth0dQr8iEBRFkyiUgVyAu0S8evdQseTHvbRicGfnSp6FbHffawginPI7nLXRCh+kgI0RsCoCAgfyBlH4TmGgpIekytcwuw2bEaJCCvUnQQU9iaxw0x3hypkXBjETL1itOInyCORB9QjafP8Wr7taK9GtbUAvTJU0Gn+vIxGrzlw4uUO8dm/Ok8xfESlbbudABaoU21rUf7b5hDhzFcF/aH4MvShf6V4zMtaKB2UwN9xCqBKiEyrmEh6icei9wuTDfsKuULDoQgQGZ5SmQHy+6KQrp+46dfviAaWLWqr4ynYTekvBU09rtMoagrM2WCobf9SzmnbdrbrLOeMhvoJSn9Saj+19cjcXGsEj46QtJ99I8E5qdw++NZFPjguYPKVDAImlyTQJ34s0=
    file:
        - "${RELEASE_FILE}"
        - doc/gbvdoc.pdf
    on:
        tags: true
