#!/usr/bin/env perl
use v5.14;
use Time::Piece;

open my $fh, '<', '../debian/changelog';

my ($version, $changes);

while (<$fh>) { 
    if ( /^[^ ]+ \(([^)]+)\)/i ) {
        $version = $1;
        $changes = "";
    } elsif (/^\s*--.*>\s+(.+)$/) {
        my $date = Time::Piece->strptime($1, "%a, %d %b %Y %T %z");
        say "### $version (".$date->strftime("%Y-%m-%d").") {.unnumbered}";
        say $changes;
    } else {        
        s/^..//mg;
        $changes .= $_;
    }
}
